### ISSUE TITLE
cookieninja with scikit-surgery template base

### ISSUE THREAD

**Issue by yidilozdemir** [UCL/scikit-surgery-stats#30]
Try this strategy for making this a cookieninja repository: 
1. in branch get the scikit-surgery template, https://github.com/SciKit-Surgery/PythonTemplate
2. made modifications to env setting and tests
3. entry point of analysis-> adjust to take library name as input

**Comment by thompson318** [comment]
This seems to be working well now at https://github.com/SciKit-Surgery/sustainable-pkg-stats
