### ISSUE TITLE
Error message: 'collections.OrderedDict object' has no attribute 'library_base_name'

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery-stats#36]
I get Error message: 'collections.OrderedDict object' has no attribute 'library_base_name' when I run the cookieninja. 
I can fix by adding 
"library_base_name": "scikit-surgery",
 "base_library_name": "{{ cookiecutter.library_base_name }}"

to the cookiecutter.json so both variables are defined. But we should probably go through the project slug and make sure the naming is consistent.

**Comment by yidilozdemir** [comment]
this is very strange, we shouldn't have a field for library_base_name

**Comment by yidilozdemir** [comment]
I have just pushed the latest version of the cookiecutter.json file, i changed a few entries' descriptions, could you do a `git pull` to make sure you have the latest version?

these are the fields it should have:

```
  "author_name": "John Smith",
  "author_email": "temp@gmail.com",
  "project_name": "Community Dashboard",
  "base_library_name": "scikit-surgery",
  "project_short_description": "A dashboard template from scikit-surgery",
  "funder": "JBFC: The Joe Bloggs Funding Council",
  "licence": ["MIT", "BSD-3", "GPL-3.0"],
  "_copy_without_render": [".github/*"]
```

**Comment by yidilozdemir** [comment]
latest changes added, inserting back "project_slug" field to refer to name of the folder, also `index.html` had a mix of variable naming between `library_base_name` and `base_library_name`. Confirmed that works now!

**Comment by thompson318** [comment]
Works for me now.
