### ISSUE TITLE
[subtask] latest_release change to latest_update + links to latest commit

### ISSUE THREAD

**Issue by yidilozdemir** [UCL/scikit-surgery-stats#38]
taking care of it in #30, partly goes well with the issue #35 

Already, most of the link references to latest release date (linking to release tags in github) don't work properly, not many packages have releases. this might better reflect activity 

I think this requires using the github.get_repo API to also get some sort of latest hash of a commit or link for the latest issue. Currently there is a badge link to release tags

**Comment by thompson318** [comment]
This is incorporated in https://github.com/SciKit-Surgery/sustainable-pkg-stats
